---
include:
 # - board: eyelash_sofle_left
#    shield: nice_view
  - board: nice_nano_v2
#   shield: nice_view_custom
    shield: sofle_right
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: eyelash_sofle_dongle_right
  - board: nice_nano_v2
    shield: sofle_left
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: eyelash_sofle_dongle_left
  - board: nice_nano_v2
    shield: settings_reset
  - board: seeeduino_xiao_ble
    shield: eyelash_sofle dongle_screen
    cmake-args: -DCONFIG_ZMK_SPLIT=y -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    #cmake-args: -DCONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=8000 #optional if logging is enabled
    #snippet: zmk-usb-logging #only enable for debugging
    artifact-name: dongle-screen
